# Generated by Django 3.2.3 on 2021-06-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'login'},
        ),
        migrations.AlterModelOptions(
            name='recharge',
            options={'verbose_name_plural': 'recharge'},
        ),
    ]
