# Generated by Django 3.2.3 on 2021-06-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recharging', '0004_rename_mobile_number_recharge_recharge_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentRecharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('recharged_number', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recharging.recharge')),
            ],
        ),
    ]
