# Generated by Django 3.2.3 on 2021-06-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharging', '0005_recentrecharges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecentRecharges',
            new_name='RecentRecharge',
        ),
    ]
