# Generated by Django 3.2.3 on 2021-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharging', '0006_rename_recentrecharges_recentrecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentrecharge',
            name='date',
            field=models.DateField(),
        ),
    ]
